/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useRef, useEffect, useCallback, useMemo, useState, JSX } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { GLTF } from "three-stdlib";

import HullOutline from "@/app/components/HullOutline";
import { BREAKPOINTS, useBreakpoints } from "@/app/hooks/breakpoints";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.SkinnedMesh;
    Plane: THREE.Mesh;
    Destruction_cell181: THREE.Mesh;
    Destruction_cell181_1: THREE.Mesh;
    Destruction_cell087: THREE.Mesh;
    Destruction_cell087_1: THREE.Mesh;
    Destruction_cell088: THREE.Mesh;
    Destruction_cell088_1: THREE.Mesh;
    Destruction_cell089: THREE.Mesh;
    Destruction_cell089_1: THREE.Mesh;
    Destruction_cell090_1: THREE.Mesh;
    Destruction_cell090_2: THREE.Mesh;
    Destruction_cell091_1: THREE.Mesh;
    Destruction_cell091_2: THREE.Mesh;
    Destruction_cell092_1: THREE.Mesh;
    Destruction_cell092_2: THREE.Mesh;
    Destruction_cell093: THREE.Mesh;
    Destruction_cell093_1: THREE.Mesh;
    Destruction_cell094: THREE.Mesh;
    Destruction_cell094_1: THREE.Mesh;
    Destruction_cell095: THREE.Mesh;
    Destruction_cell095_1: THREE.Mesh;
    Destruction_cell098: THREE.Mesh;
    Destruction_cell098_1: THREE.Mesh;
    Destruction_cell099: THREE.Mesh;
    Destruction_cell099_1: THREE.Mesh;
    Destruction_cell100: THREE.Mesh;
    Destruction_cell100_1: THREE.Mesh;
    Destruction_cell101: THREE.Mesh;
    Destruction_cell101_1: THREE.Mesh;
    Destruction_cell102: THREE.Mesh;
    Destruction_cell102_1: THREE.Mesh;
    Destruction_cell103: THREE.Mesh;
    Destruction_cell103_1: THREE.Mesh;
    Destruction_cell104: THREE.Mesh;
    Destruction_cell104_1: THREE.Mesh;
    Destruction_cell105: THREE.Mesh;
    Destruction_cell105_1: THREE.Mesh;
    Destruction_cell106: THREE.Mesh;
    Destruction_cell106_1: THREE.Mesh;
    Destruction_cell107: THREE.Mesh;
    Destruction_cell107_1: THREE.Mesh;
    Destruction_cell108: THREE.Mesh;
    Destruction_cell108_1: THREE.Mesh;
    Destruction_cell109: THREE.Mesh;
    Destruction_cell109_1: THREE.Mesh;
    Destruction_cell110: THREE.Mesh;
    Destruction_cell110_1: THREE.Mesh;
    Destruction_cell111: THREE.Mesh;
    Destruction_cell111_1: THREE.Mesh;
    Destruction_cell112: THREE.Mesh;
    Destruction_cell112_1: THREE.Mesh;
    Destruction_cell113: THREE.Mesh;
    Destruction_cell113_1: THREE.Mesh;
    Destruction_cell114: THREE.Mesh;
    Destruction_cell114_1: THREE.Mesh;
    Destruction_cell115: THREE.Mesh;
    Destruction_cell115_1: THREE.Mesh;
    Destruction_cell116: THREE.Mesh;
    Destruction_cell116_1: THREE.Mesh;
    Destruction_cell117: THREE.Mesh;
    Destruction_cell117_1: THREE.Mesh;
    Destruction_cell118: THREE.Mesh;
    Destruction_cell118_1: THREE.Mesh;
    Destruction_cell119: THREE.Mesh;
    Destruction_cell119_1: THREE.Mesh;
    Destruction_cell120: THREE.Mesh;
    Destruction_cell120_1: THREE.Mesh;
    Destruction_cell121: THREE.Mesh;
    Destruction_cell121_1: THREE.Mesh;
    Destruction_cell122: THREE.Mesh;
    Destruction_cell122_1: THREE.Mesh;
    Destruction_cell123: THREE.Mesh;
    Destruction_cell123_1: THREE.Mesh;
    Destruction_cell124: THREE.Mesh;
    Destruction_cell124_1: THREE.Mesh;
    Destruction_cell125: THREE.Mesh;
    Destruction_cell125_1: THREE.Mesh;
    Destruction_cell126: THREE.Mesh;
    Destruction_cell126_1: THREE.Mesh;
    Destruction_cell127: THREE.Mesh;
    Destruction_cell127_1: THREE.Mesh;
    Destruction_cell128: THREE.Mesh;
    Destruction_cell128_1: THREE.Mesh;
    Destruction_cell129: THREE.Mesh;
    Destruction_cell129_1: THREE.Mesh;
    Destruction_cell130: THREE.Mesh;
    Destruction_cell130_1: THREE.Mesh;
    Destruction_cell131: THREE.Mesh;
    Destruction_cell131_1: THREE.Mesh;
    Destruction_cell132: THREE.Mesh;
    Destruction_cell132_1: THREE.Mesh;
    Destruction_cell133: THREE.Mesh;
    Destruction_cell133_1: THREE.Mesh;
    Destruction_cell134: THREE.Mesh;
    Destruction_cell134_1: THREE.Mesh;
    Destruction_cell135: THREE.Mesh;
    Destruction_cell135_1: THREE.Mesh;
    Destruction_cell136: THREE.Mesh;
    Destruction_cell136_1: THREE.Mesh;
    Destruction_cell137: THREE.Mesh;
    Destruction_cell137_1: THREE.Mesh;
    Destruction_cell138: THREE.Mesh;
    Destruction_cell138_1: THREE.Mesh;
    Destruction_cell139: THREE.Mesh;
    Destruction_cell139_1: THREE.Mesh;
    Destruction_cell140: THREE.Mesh;
    Destruction_cell140_1: THREE.Mesh;
    Destruction_cell141: THREE.Mesh;
    Destruction_cell141_1: THREE.Mesh;
    Destruction_cell142: THREE.Mesh;
    Destruction_cell142_1: THREE.Mesh;
    Destruction_cell143: THREE.Mesh;
    Destruction_cell143_1: THREE.Mesh;
    Destruction_cell144: THREE.Mesh;
    Destruction_cell144_1: THREE.Mesh;
    Destruction_cell145: THREE.Mesh;
    Destruction_cell145_1: THREE.Mesh;
    Destruction_cell146: THREE.Mesh;
    Destruction_cell146_1: THREE.Mesh;
    Destruction_cell147: THREE.Mesh;
    Destruction_cell147_1: THREE.Mesh;
    Destruction_cell001: THREE.Mesh;
    Destruction_cell149: THREE.Mesh;
    Destruction_cell149_1: THREE.Mesh;
    Destruction_cell150: THREE.Mesh;
    Destruction_cell150_1: THREE.Mesh;
    Destruction_cell151: THREE.Mesh;
    Destruction_cell151_1: THREE.Mesh;
    Destruction_cell152: THREE.Mesh;
    Destruction_cell152_1: THREE.Mesh;
    Destruction_cell153: THREE.Mesh;
    Destruction_cell153_1: THREE.Mesh;
    Destruction_cell154: THREE.Mesh;
    Destruction_cell154_1: THREE.Mesh;
    Destruction_cell155: THREE.Mesh;
    Destruction_cell155_1: THREE.Mesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    ["Material.001"]: THREE.MeshPhysicalMaterial;
    ["Material.002"]: THREE.MeshPhysicalMaterial;
    Inside: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | "Idle"
  | "Destruction_cellAction"
  | "Destruction_cell.004Action"
  | "Destruction_cell.006Action"
  | "Destruction_cell.007Action"
  | "Destruction_cell.008Action"
  | "Destruction_cell.009Action"
  | "Destruction_cell.010Action"
  | "Destruction_cell.011Action"
  | "Destruction_cell.012Action"
  | "Destruction_cell.014Action"
  | "Destruction_cell.016Action"
  | "Destruction_cell.017Action"
  | "Destruction_cell.024Action"
  | "Destruction_cell.025Action"
  | "Destruction_cell.027Action"
  | "Destruction_cell.029Action"
  | "Destruction_cell.030Action"
  | "Destruction_cell.031Action"
  | "Destruction_cell.032Action"
  | "Destruction_cell.033Action"
  | "Destruction_cell.034Action"
  | "Destruction_cell.035Action"
  | "Destruction_cell.036Action"
  | "Destruction_cell.037Action"
  | "Destruction_cell.039Action"
  | "Destruction_cell.040Action"
  | "Destruction_cell.041Action"
  | "Destruction_cell.042Action"
  | "Destruction_cell.043Action"
  | "Destruction_cell.044Action"
  | "Destruction_cell.045Action"
  | "Destruction_cell.050Action"
  | "Destruction_cell.051Action"
  | "Destruction_cell.052Action"
  | "Destruction_cell.054Action"
  | "Destruction_cell.055Action"
  | "Destruction_cell.056Action"
  | "Destruction_cell.057Action"
  | "Destruction_cell.059Action"
  | "Destruction_cell.060Action"
  | "Destruction_cell.062Action"
  | "Destruction_cell.064Action"
  | "Destruction_cell.065Action"
  | "Destruction_cell.066Action"
  | "Destruction_cell.067Action"
  | "Destruction_cell.070Action"
  | "Destruction_cell.071Action"
  | "Destruction_cell.073Action"
  | "Destruction_cell.074Action"
  | "Destruction_cell.075Action"
  | "Destruction_cell.076Action"
  | "Destruction_cell.077Action"
  | "Destruction_cell.081Action"
  | "Destruction_cell.082Action"
  | "Destruction_cell.083Action"
  | "Destruction_cell.084Action"
  | "Destruction_cell.086Action"
  | "Destruction_cell.090Action"
  | "Destruction_cell.091Action"
  | "Destruction_cell.092Action"
  | "Destruction_cell.001Action"
  | "Destruction_cell.002Action"
  | "Destruction_cell.003Action"
  | "Destruction_cell.005Action"
  | "Destruction_cell.013Action"
  | "Destruction_cell.015Action"
  | "Destruction_cell.018Action"
  | "Destruction_cell.019Action";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

/**
 * Slack around the silhouette, in CSS pixels — not a scale factor. The figure
 * is a tall, thin thing (~42x133px on a desktop hero, ~22x70 on a phone), so
 * scaling the box to make it wide enough to hit makes it absurdly tall: the
 * 2.0x it takes to get a phone-sized figure to a 44px target also hangs 36px of
 * dead space above its head. A fixed pixel margin grows the axis that needs it
 * and leaves the long one alone.
 */
const HIT_MARGIN = 4;

/**
 * Below md the pointer is a fingertip and the figure is half the size, so the
 * same target has to be built out of a lot more slack — 22px of body plus this
 * on either side clears the ~44px both platforms ask for.
 */
const HIT_MARGIN_TOUCH = 16;

/**
 * Frames between rebuilds of the hit box. Measuring it walks every vertex, and
 * the idle moves the silhouette by a fraction of a percent per frame, so a few
 * frames of lag is invisible and this stays off the per-frame budget.
 */
const HIT_REFRESH = 6;

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const unified = useRef<THREE.Group>(null);
  const fractured = useRef<THREE.Group>(null);
  const skin = useRef<THREE.SkinnedMesh>(null);
  const hit = useRef<THREE.Mesh>(null);
  const [hovered, setHovered] = useState(false);
  const isAnimating = useRef(false);

  // the same seam the rest of the scene splits on — below md <Scene /> drops
  // the whole group and <Steps /> shrinks it, so the figure this has to cover
  // is a different size there too
  const { up } = useBreakpoints(BREAKPOINTS, { clientOnly: true });
  const margin = up.md ? HIT_MARGIN : HIT_MARGIN_TOUCH;

  const { nodes, materials, animations } = useGLTF(
    "/models/test-material.glb",
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);

  const playIdle = useCallback(() => {
    const idleAction = actions?.["Idle"];

    if (!idleAction) return;

    idleAction.reset().play();
  }, [actions]);

  useEffect(() => {
    playIdle();
    unified.current!.visible = true;
    fractured.current!.visible = false;

    return () => {
      const idleAction = actions?.["Idle"];
      idleAction?.stop();
    };
  }, [actions, playIdle]);

  /**
   * Clone GLTF material so hover effects
   * don't mutate the shared original material.
   */
  const material = useMemo(() => {
    const cloned = materials["Material.002"].clone();

    cloned.color.set("black");
    cloned.emissive = new THREE.Color("white");
    cloned.emissiveIntensity = 0;

    return cloned;
  }, [materials]);

  /**
   * Hover fill effect
   */
  useEffect(() => {
    if (isAnimating.current) return;

    material.color.set(hovered ? "white" : "black");

    // stronger white fill
    material.emissiveIntensity = hovered ? 1 : 0;

    material.needsUpdate = true;

    if (hovered) {
      document.body.style.cursor = "pointer";
    } else {
      document.body.style.cursor = "default";
    }
  }, [hovered, material, isAnimating]);

  /**
   * <Steps /> drops the figure out of the scene once the staircase has scrolled
   * away, and an unmounted mesh never gets its onPointerLeave — so the pointer
   * cursor would stick for the rest of the page if it left mid-hover.
   */
  useEffect(
    () => () => {
      document.body.style.cursor = "default";
    },
    [],
  );

  /**
   * Keeps the pointer target (see the box below <HullOutline />) wrapped around
   * whatever pose three is drawing.
   *
   * It has to be rebuilt rather than measured once: three only ever computes a
   * skinned mesh's bounds on demand — the first frustum cull — and then caches
   * them forever, so anything derived from that snapshot drifts as soon as the
   * idle starts moving. `computeBoundingBox()` runs the same skinning the
   * shader does, so the box is exactly the figure on screen.
   */
  const hitSize = useMemo(() => new THREE.Vector3(), []);
  const hitCentre = useMemo(() => new THREE.Vector3(), []);
  const worldScale = useMemo(() => new THREE.Vector3(), []);
  const tmpVec = useMemo(() => new THREE.Vector3(), []);
  const frame = useRef(0);

  useFrame(({ camera, size }) => {
    const mesh = skin.current;
    const target = hit.current;

    if (!mesh || !target) return;
    if (frame.current++ % HIT_REFRESH) return;

    mesh.computeBoundingBox();
    const box = mesh.boundingBox!;

    // the cached-bounds problem again, this time for the sphere the renderer
    // culls against: refresh it from the box we just measured so the figure
    // can't be culled out of a frame it's still standing in. Taken before the
    // margin goes on, so culling reads the body rather than the target.
    mesh.boundingSphere ??= new THREE.Sphere();
    box.getBoundingSphere(mesh.boundingSphere);

    // Grow the box by a fixed number of screen pixels. Expanding symmetrically
    // leaves the centre where it is, so it can be measured first and reused.
    box.getCenter(hitCentre);

    const perspective = camera as THREE.PerspectiveCamera;
    if (perspective.isPerspectiveCamera) {
      const distance = mesh
        .localToWorld(tmpVec.copy(hitCentre))
        .distanceTo(camera.position);
      // the view frustum's height in world units at the figure's depth, over
      // the viewport in CSS pixels, then out of world units and into the local
      // space the box lives in
      const perPixel =
        (2 * Math.tan((perspective.fov * Math.PI) / 360) * distance) /
        size.height;

      box.expandByScalar(
        (margin * perPixel) / (mesh.getWorldScale(worldScale).x || 1),
      );
    }

    // the box is in the skinned mesh's local space, which is exactly the space
    // this mesh's children live in — no conversion to do
    target.position.copy(hitCentre);
    target.scale.copy(box.getSize(hitSize));
  });

  const handleClick = useCallback(() => {
    if (isAnimating.current) return;

    document.body.style.cursor = "default";
    isAnimating.current = true;
    unified.current!.visible = false;
    fractured.current!.visible = true;

    Object.keys(actions).forEach((key) => {
      if (key !== "Idle") {
        const action = actions[key]!;
        action.reset();
        action.timeScale = 1;
        action.clampWhenFinished = true;
        action.setLoop(THREE.LoopOnce, 1);
        action.play();
      }
    });
  }, [actions]);

  // Reverse each action once it finishes playing forward
  useEffect(() => {
    const mixer = Object.values(actions)[0]?.getMixer();
    if (!mixer) return;

    let count = 0;

    const onFinished = (e: any) => {
      const action = e.action as THREE.AnimationAction;

      // Only reverse actions that just finished playing forward
      if (action.timeScale > 0) {
        action.paused = false;
        action.timeScale = -1;
        action.play();
      } else {
        const total = Object.keys(actions).length - 2;
        count++;

        if (count >= total + 1) {
          fractured.current!.visible = false;
          unified.current!.visible = true;
          isAnimating.current = false;
          material.emissiveIntensity = 0;
          material.needsUpdate = true;
        }
      }
      // if timeScale < 0 here, it just finished reversing — leave it stopped
    };

    mixer.addEventListener("finished", onFinished);
    return () => {
      mixer.removeEventListener("finished", onFinished);
      const idleAction = actions?.["Idle"];
      idleAction?.stop();
    };
  }, [actions, material]);

  /**
   * Shared by every fractured cell's inner face. Building it inside the render
   * body handed all ~68 meshes a brand new material — and a brand new shader
   * compile — on every single re-render.
   */
  const innerMaterial = useMemo(
    () =>
      new THREE.MeshNormalMaterial({
        transparent: true,
        opacity: 0.95,
      }),
    [],
  );

  useEffect(() => () => innerMaterial.dispose(), [innerMaterial]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Armature"
        ref={unified}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <skinnedMesh
          ref={skin}
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={material}
          skeleton={nodes.Cube.skeleton}
        >
          <HullOutline />

          {/* Pointer target for the figure as a whole. The handlers used to sit
              on the skinned mesh itself, which answered only where a triangle
              actually was — on a body this small on screen, the gaps between
              the arms and either side of the legs read as dead spots, and every
              pointermove paid a bone transform per vertex to find them. A box
              around the live pose is twelve triangles, covers the silhouette in
              one piece, and carries the margin a fingertip needs on touch;
              `material.visible` skips the draw and leaves it raycastable. */}
          <mesh
            ref={hit}
            onPointerEnter={() => setHovered(true)}
            onPointerLeave={() => setHovered(false)}
            onClick={handleClick}
          >
            <boxGeometry />
            <meshBasicMaterial visible={false} />
          </mesh>
        </skinnedMesh>
        <primitive object={nodes.mixamorigHips} />
      </group>
      <group ref={fractured}>
        <group name="Destruction_cell" position={[-0.214, 1.007, -0.019]}>
          <mesh
            name="Destruction_cell181"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell181.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell181_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell181_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell004" position={[-0.004, 2.288, 0.088]}>
          <mesh
            name="Destruction_cell087"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell087.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell087_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell087_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell006" position={[0.065, 1.38, -0.116]}>
          <mesh
            name="Destruction_cell088"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell088.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell088_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell088_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell007" position={[0.146, 0.295, 0.008]}>
          <mesh
            name="Destruction_cell089"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell089.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell089_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell089_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell008" position={[0.232, 1.693, -0.078]}>
          <mesh
            name="Destruction_cell090_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell090_1.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell090_2"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell090_2.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell009" position={[0, 1.677, -0.017]}>
          <mesh
            name="Destruction_cell091_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell091_1.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell091_2"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell091_2.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell010" position={[0.127, 2.002, -0.038]}>
          <mesh
            name="Destruction_cell092_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell092_1.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell092_2"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell092_2.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell011" position={[-0.262, 1.952, -0.086]}>
          <mesh
            name="Destruction_cell093"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell093.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell093_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell093_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell012" position={[0.181, 1.241, -0.023]}>
          <mesh
            name="Destruction_cell094"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell094.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell094_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell094_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell014" position={[-0.069, 2.286, -0.098]}>
          <mesh
            name="Destruction_cell095"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell095.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell095_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell095_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell016" position={[0.075, 2.189, 0.036]}>
          <mesh
            name="Destruction_cell098"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell098.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell098_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell098_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell017" position={[-0.199, 0.375, -0.003]}>
          <mesh
            name="Destruction_cell099"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell099.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell099_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell099_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell024" position={[-0.089, 2.355, -0.071]}>
          <mesh
            name="Destruction_cell100"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell100.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell100_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell100_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell025" position={[0.221, 1.5, 0.006]}>
          <mesh
            name="Destruction_cell101"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell101.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell101_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell101_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell027" position={[-0.197, 1.564, -0.069]}>
          <mesh
            name="Destruction_cell102"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell102.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell102_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell102_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell029" position={[0.285, 0.023, 0.096]}>
          <mesh
            name="Destruction_cell103"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell103.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell103_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell103_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell030" position={[-0.127, 1.591, 0.077]}>
          <mesh
            name="Destruction_cell104"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell104.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell104_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell104_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell031" position={[0.27, 1.966, -0.066]}>
          <mesh
            name="Destruction_cell105"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell105.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell105_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell105_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell032" position={[0.011, 2.296, -0.028]}>
          <mesh
            name="Destruction_cell106"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell106.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell106_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell106_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell033" position={[-0.301, 1.748, -0.109]}>
          <mesh
            name="Destruction_cell107"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell107.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell107_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell107_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell034" position={[-0.09, 2.33, 0.023]}>
          <mesh
            name="Destruction_cell108"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell108.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell108_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell108_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell035" position={[-0.093, 1.036, 0]}>
          <mesh
            name="Destruction_cell109"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell109.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell109_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell109_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell036" position={[-0.197, 1.742, -0.11]}>
          <mesh
            name="Destruction_cell110"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell110.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell110_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell110_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell037" position={[-0.247, 0.134, 0.025]}>
          <mesh
            name="Destruction_cell111"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell111.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell111_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell111_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell039" position={[0.277, 1.807, -0.066]}>
          <mesh
            name="Destruction_cell112"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell112.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell112_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell112_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell040" position={[0.214, 1.185, 0.088]}>
          <mesh
            name="Destruction_cell113"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell113.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell113_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell113_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell041" position={[-0.182, 0.727, 0.043]}>
          <mesh
            name="Destruction_cell114"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell114.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell114_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell114_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell042" position={[0.206, 1.021, 0.032]}>
          <mesh
            name="Destruction_cell115"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell115.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell115_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell115_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell043" position={[-0.195, 0.101, -0.024]}>
          <mesh
            name="Destruction_cell116"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell116.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell116_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell116_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell044" position={[0.103, 0.795, 0.092]}>
          <mesh
            name="Destruction_cell117"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell117.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell117_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell117_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell045" position={[0.208, 0.042, -0.006]}>
          <mesh
            name="Destruction_cell118"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell118.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell118_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell118_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell050" position={[0.235, 0.769, 0.113]}>
          <mesh
            name="Destruction_cell119"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell119.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell119_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell119_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell051" position={[-0.166, 1.271, -0.013]}>
          <mesh
            name="Destruction_cell120"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell120.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell120_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell120_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell052" position={[-0.006, 2.101, 0.041]}>
          <mesh
            name="Destruction_cell121"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell121.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell121_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell121_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell054" position={[0.184, 0.191, -0.058]}>
          <mesh
            name="Destruction_cell122"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell122.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell122_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell122_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell055" position={[0.181, 0.836, 0.067]}>
          <mesh
            name="Destruction_cell123"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell123.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell123_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell123_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell056" position={[0.177, 0.443, 0.016]}>
          <mesh
            name="Destruction_cell124"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell124.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell124_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell124_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell057" position={[0.02, 1.52, -0.047]}>
          <mesh
            name="Destruction_cell125"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell125.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell125_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell125_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell059" position={[-0.308, 1.51, -0.049]}>
          <mesh
            name="Destruction_cell126"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell126.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell126_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell126_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell060" position={[0.114, 0.925, 0.129]}>
          <mesh
            name="Destruction_cell127"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell127.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell127_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell127_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell062" position={[-0.067, 2.09, -0.092]}>
          <mesh
            name="Destruction_cell128"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell128.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell128_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell128_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell064" position={[0.191, 0.902, 0.141]}>
          <mesh
            name="Destruction_cell129"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell129.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell129_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell129_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell065" position={[-0.256, 1.159, 0.151]}>
          <mesh
            name="Destruction_cell130"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell130.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell130_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell130_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell066" position={[-0.273, 1.421, -0.019]}>
          <mesh
            name="Destruction_cell131"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell131.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell131_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell131_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell067" position={[-0.196, 2.043, -0.067]}>
          <mesh
            name="Destruction_cell132"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell132.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell132_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell132_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell070" position={[0.072, 1.228, 0.068]}>
          <mesh
            name="Destruction_cell133"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell133.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell133_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell133_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell071" position={[0.081, 1.385, 0.126]}>
          <mesh
            name="Destruction_cell134"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell134.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell134_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell134_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell073" position={[-0.242, 1.204, 0.07]}>
          <mesh
            name="Destruction_cell135"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell135.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell135_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell135_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell074" position={[0.162, 0.638, 0.067]}>
          <mesh
            name="Destruction_cell136"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell136.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell136_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell136_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell075" position={[-0.226, 0.147, -0.068]}>
          <mesh
            name="Destruction_cell137"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell137.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell137_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell137_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell076" position={[-0.124, 1.971, -0.007]}>
          <mesh
            name="Destruction_cell138"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell138.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell138_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell138_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell077" position={[-0.282, 1.356, 0.025]}>
          <mesh
            name="Destruction_cell139"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell139.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell139_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell139_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell081" position={[-0.093, 1.285, 0.12]}>
          <mesh
            name="Destruction_cell140"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell140.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell140_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell140_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell082" position={[-0.092, 1.756, 0.103]}>
          <mesh
            name="Destruction_cell141"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell141.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell141_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell141_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell083" position={[-0.026, 1.146, -0.088]}>
          <mesh
            name="Destruction_cell142"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell142.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell142_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell142_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell084" position={[-0.134, 1.442, -0.049]}>
          <mesh
            name="Destruction_cell143"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell143.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell143_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell143_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell086" position={[0.068, 1.817, 0.079]}>
          <mesh
            name="Destruction_cell144"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell144.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell144_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell144_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell090" position={[0.061, 1.86, -0.168]}>
          <mesh
            name="Destruction_cell145"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell145.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell145_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell145_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell091" position={[-0.152, 0.99, 0.073]}>
          <mesh
            name="Destruction_cell146"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell146.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell146_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell146_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell092" position={[0.333, 1.613, -0.049]}>
          <mesh
            name="Destruction_cell147"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell147.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell147_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell147_1.geometry}
            material={innerMaterial}
          />
        </group>
        <mesh
          name="Destruction_cell001"
          castShadow
          receiveShadow
          geometry={nodes.Destruction_cell001.geometry}
          material={innerMaterial}
          position={[-0.147, 0.24, -0.038]}
        />
        <group name="Destruction_cell002" position={[-0.26, 1.551, -0.079]}>
          <mesh
            name="Destruction_cell149"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell149.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell149_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell149_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell003" position={[0.084, 0.991, 0.047]}>
          <mesh
            name="Destruction_cell150"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell150.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell150_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell150_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell005" position={[0.055, 0.833, -0.01]}>
          <mesh
            name="Destruction_cell151"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell151.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell151_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell151_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell013" position={[-0.2, 1.374, -0.049]}>
          <mesh
            name="Destruction_cell152"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell152.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell152_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell152_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell015" position={[-0.092, 2.225, 0.034]}>
          <mesh
            name="Destruction_cell153"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell153.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell153_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell153_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell018" position={[-0.228, 1.141, 0.146]}>
          <mesh
            name="Destruction_cell154"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell154.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell154_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell154_1.geometry}
            material={innerMaterial}
          />
        </group>
        <group name="Destruction_cell019" position={[-0.231, 1.453, -0.022]}>
          <mesh
            name="Destruction_cell155"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell155.geometry}
            material={materials["Material.002"]}
          >
            <HullOutline />
          </mesh>
          <mesh
            name="Destruction_cell155_1"
            castShadow
            receiveShadow
            geometry={nodes.Destruction_cell155_1.geometry}
            material={innerMaterial}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/test-material.glb");
